    $(document).ready(function(){
        $("input#Vinku").hide();
        $("#hide1").hide();
        $("#more1").hide();
        $(".button1").click(function(){
        $(".button1").show();
        $("#more1").show();
        $("input").slideDown("fast");
        }); 
        $("#hide1").click(function(){
        $("input#").slideUp("fast"); 
        $("#hide1").hide();
        $("#more1").hide();
        });        
    });

    $(document).ready(function(){
        $("button#Naiko")
    })