    //Vinku
    $(document).ready(function(){
        $("input#Vinku").hide();
        $("#hide1").hide();
        $("#more1").hide();
        $(".button1").click(function(){
        $(".button1").show();
        $("#more1").show();
        $("input#Vinku").slideDown("fast");
        }); 
        $("#hide1").click(function(){
        $("input#Vinku").slideUp("fast"); 
        $("#hide1").hide();
        $("#more1").hide();
        });        
    });
    //Vascor
    $(document).ready(function(){
        $("input#Vascor").hide();
        $("#hide2").hide();
        $("#more2").hide();
        $(".button2").click(function(){
        $(".button2").show();
        $("#more2").show();
        $("input#Vascor").slideDown("fast");
        }); 
        $("#hide2").click(function(){
        $("input#Vascor").slideUp("fast"); 
        $("#hide2").hide();
        $("#more2").hide();
        });        
    });
    //Peku
    $(document).ready(function(){
        $("input#Peku").hide();
        $("#hide3").hide();
        $("#more3").hide();
        $(".button3").click(function(){
        $(".button3").show();
        $("#more3").show();
        $("input#Peku").slideDown("fast");
        }); 
        $("#hide3").click(function(){
        $("input#Peku").slideUp("fast"); 
        $("#hide3").hide();
        $("#more3").hide();
        });        
    });
    //Psycho
    $(document).ready(function(){
        $("input#Psycho").hide();
        $("#hide4").hide();
        $("#more4").hide();
        $(".button4").click(function(){
        $(".button4").show();
        $("#more4").show();
        $("input#Psycho").slideDown("fast");
        }); 
        $("#hide4").click(function(){
        $("input#Psycho").slideUp("fast"); 
        $("#hide4").hide();
        $("#more4").hide();
        });        
    });
    
    //Cubesa
    $(document).ready(function(){
        $("input#Cubesa").hide();
        $("#hide5").hide();
        $("#more5").hide();
        $(".button5").click(function(){
        $(".button5").show();
        $("#more5").show();
        $("input#Cubesa").slideDown("fast");
        }); 
        $("#hide5").click(function(){
        $("input#Cubesa").slideUp("fast"); 
        $("#hide5").hide();
        $("#more5").hide();
        });        
    });
    //North
    $(document).ready(function(){
        $("input#North").hide();
        $("#hide6").hide();
        $("#more6").hide();
        $(".button6").click(function(){
        $(".button6").show();
        $("#more6").show();
        $("input#North").slideDown("fast");
        }); 
        $("#hide6").click(function(){
        $("input#North").slideUp("fast"); 
        $("#hide6").hide();
        $("#more6").hide();
        });        
    });
    //Blue
    $(document).ready(function(){
        $("input#Blue").hide();
        $("#hide8").hide();
        $("#more8").hide();
        $(".button8").click(function(){
        $(".button8").show();
        $("#more8").show();
        $("input#Blue").slideDown("fast");
        }); 
        $("#hide8").click(function(){
        $("input#Blue").slideUp("fast"); 
        $("#hide8").hide();
        $("#more8").hide();
        });        
    });
    //Winter
    $(document).ready(function(){
        $("input#Winter").hide();
        $("#hide9").hide();
        $("#more9").hide();
        $(".button9").click(function(){
        $(".button9").show();
        $("#more9").show();
        $("input#Winter").slideDown("fast");
        }); 
        $("#hide9").click(function(){
        $("input#Winter").slideUp("fast"); 
        $("#hide9").hide();
        $("#more9").hide();
        });        
    });
    //Nemo
    $(document).ready(function(){
        $("input#Nemo").hide();
        $("#hide10").hide();
        $("#more10").hide();
        $(".button10").click(function(){
        $(".button10").show();
        $("#more10").show();
        $("input#Nemo").slideDown("fast");
        }); 
        $("#hide10").click(function(){
        $("input#Nemo").slideUp("fast"); 
        $("#hide10").hide();
        $("#more10").hide();
        });        
    })
    //Zen
    $(document).ready(function(){
        $("input#Zen").hide();
        $("#hide11").hide();
        $("#more11").hide();
        $(".button11").click(function(){
        $(".button11").show();
        $("#more11").show();
        $("input#Zen").slideDown("fast");
        }); 
        $("#hide11").click(function(){
        $("input#Zen").slideUp("fast"); 
        $("#hide11").hide();
        $("#more11").hide();
        });        
    })
    //S'ghetti
    $(document).ready(function(){
        $("input#Sghetti").hide();
        $("#hide12").hide();
        $("#more12").hide();
        $(".button12").click(function(){
        $(".button12").show();
        $("#more12").show();
        $("input#Sghetti").slideDown("fast");
        }); 
        $("#hide12").click(function(){
        $("input#Sghetti").slideUp("fast"); 
        $("#hide12").hide();
        $("#more12").hide();
        });        
    })
    //Waterholic
    $(document).ready(function(){
        $("input#Waterholic").hide();
        $("#hide13").hide();
        $("#more13").hide();
        $(".button13").click(function(){
        $(".button13").show();
        $("#more13").show();
        $("input#Waterholic").slideDown("fast");
        }); 
        $("#hide13").click(function(){
        $("input#Waterholic").slideUp("fast"); 
        $("#hide13").hide();
        $("#more13").hide();
        });        
    })
    //Naiko
    $(document).ready(function(){
        $("input#Naiko").hide();
        $("#hide14").hide();
        $("#more14").hide();
        $(".button14").click(function(){
        $(".button14").show();
        $("#more14").show();
        $("input#Naiko").slideDown("fast");
        }); 
        $("#hide14").click(function(){
        $("input#Naiko").slideUp("fast"); 
        $("#hide14").hide();
        $("#more14").hide();
        });        
    })
    //Phoe
    $(document).ready(function(){
        $("input#Phoe").hide();
        $("#hide7").hide();
        $("#more7").hide();
        $(".button7").click(function(){
        $(".button7").show();
        $("#more7").show();
        $("input#Phoe").slideDown("fast");
        }); 
        $("#hide7").click(function(){
        $("input#Phoe").slideUp("fast"); 
        $("#hide7").hide();
        $("#more7").hide();
        });        
    })